// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEyZU71MRwnJQz42i61Bmv_YzLm-CTejg',
    appId: '1:349156142110:web:f11aa3e85429b17c4cd20f',
    messagingSenderId: '349156142110',
    projectId: 'tripmate-25b3d',
    authDomain: 'tripmate-25b3d.firebaseapp.com',
    storageBucket: 'tripmate-25b3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0Sqn07QbK4OBlxpphY6rOMLxlTjmVfM',
    appId: '1:349156142110:android:121f2c408408b21a4cd20f',
    messagingSenderId: '349156142110',
    projectId: 'tripmate-25b3d',
    storageBucket: 'tripmate-25b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJL2a6b70RWgVZ-mxFakg9IvrkDaE9vQ',
    appId: '1:349156142110:ios:8a548ce58f209e1a4cd20f',
    messagingSenderId: '349156142110',
    projectId: 'tripmate-25b3d',
    storageBucket: 'tripmate-25b3d.firebasestorage.app',
    iosBundleId: 'com.example.tripmateApp',
  );
}
